namespace OpenGL;

public enum ArbMultitexture
{
	Texture0Arb = 33984,
	Texture1Arb,
	Texture2Arb,
	Texture3Arb,
	Texture4Arb,
	Texture5Arb,
	Texture6Arb,
	Texture7Arb,
	Texture8Arb,
	Texture9Arb,
	Texture10Arb,
	Texture11Arb,
	Texture12Arb,
	Texture13Arb,
	Texture14Arb,
	Texture15Arb,
	Texture16Arb,
	Texture17Arb,
	Texture18Arb,
	Texture19Arb,
	Texture20Arb,
	Texture21Arb,
	Texture22Arb,
	Texture23Arb,
	Texture24Arb,
	Texture25Arb,
	Texture26Arb,
	Texture27Arb,
	Texture28Arb,
	Texture29Arb,
	Texture30Arb,
	Texture31Arb,
	ActiveTextureArb,
	ClientActiveTextureArb,
	MaxTextureUnitsArb
}
