using System;

namespace Foundation;

[AttributeUsage(AttributeTargets.Class | AttributeTargets.Interface)]
public sealed class ModelAttribute : Attribute
{
	public string Name { get; set; }

	public bool AutoGeneratedName { get; set; }
}
