global using Avalonia.Metadata;
global using Avalonia.Controls;
global using Avalonia.Controls.Platform;
global using Avalonia.Platform;
global using Avalonia.Layout;
global using Avalonia.Media;
global using Avalonia.Media.Immutable;
global using Avalonia.Utilities; 
global using Avalonia.Controls.Templates;
global using Avalonia.Controls.Presenters;
global using Avalonia.Collections;
global using Avalonia;
global using WebViewCore.Events;
global using WebViewCore;
global using AvaloniaWebView.Shared;
global using WebViewCore.Configurations;
global using System.Collections.ObjectModel; 
global using AvaloniaBlazorWebView.Core;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.WebView;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.Extensions.FileProviders;
global using Microsoft.Extensions.Primitives;
global using AvaloniaBlazorWebView.Components;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using AvaloniaBlazorWebView.Configurations;
global using System.Threading.Channels;
global using System.Reflection;


global using AvaloniaUIDispatcher = Avalonia.Threading.Dispatcher;