namespace OpenGL;

public enum ExtTexture
{
	Alpha4Ext = 32827,
	Alpha8Ext,
	Alpha12Ext,
	Alpha16Ext,
	Luminance4Ext,
	Luminance8Ext,
	Luminance12Ext,
	Luminance16Ext,
	Luminance4Alpha4Ext,
	Luminance6Alpha2Ext,
	Luminance8Alpha8Ext,
	Luminance12Alpha4Ext,
	Luminance12Alpha12Ext,
	Luminance16Alpha16Ext,
	IntensityExt,
	Intensity4Ext,
	Intensity8Ext,
	Intensity12Ext,
	Intensity16Ext,
	Rgb2Ext,
	Rgb4Ext,
	Rgb5Ext,
	Rgb8Ext,
	Rgb10Ext,
	Rgb12Ext,
	Rgb16Ext,
	Rgba2Ext,
	Rgba4Ext,
	Rgb5A1Ext,
	Rgba8Ext,
	Rgb10A2Ext,
	Rgba12Ext,
	Rgba16Ext,
	TextureRedSizeExt,
	TextureGreenSizeExt,
	TextureBlueSizeExt,
	TextureAlphaSizeExt,
	TextureLuminanceSizeExt,
	TextureIntensitySizeExt,
	ReplaceExt,
	ProxyTexture1DExt,
	ProxyTexture2DExt,
	TextureTooLargeExt
}
