namespace OpenGL;

public enum ExtVertexArray
{
	VertexArrayExt = 32884,
	NormalArrayExt,
	ColorArrayExt,
	IndexArrayExt,
	TextureCoordArrayExt,
	EdgeFlagArrayExt,
	VertexArraySizeExt,
	VertexArrayTypeExt,
	VertexArrayStrideExt,
	VertexArrayCountExt,
	NormalArrayTypeExt,
	NormalArrayStrideExt,
	NormalArrayCountExt,
	ColorArraySizeExt,
	ColorArrayTypeExt,
	ColorArrayStrideExt,
	ColorArrayCountExt,
	IndexArrayTypeExt,
	IndexArrayStrideExt,
	IndexArrayCountExt,
	TextureCoordArraySizeExt,
	TextureCoordArrayTypeExt,
	TextureCoordArrayStrideExt,
	TextureCoordArrayCountExt,
	EdgeFlagArrayStrideExt,
	EdgeFlagArrayCountExt,
	VertexArrayPointerExt,
	NormalArrayPointerExt,
	ColorArrayPointerExt,
	IndexArrayPointerExt,
	TextureCoordArrayPointerExt,
	EdgeFlagArrayPointerExt
}
