global using Linux.WebView.Core.Extensions;
global using Linux.WebView.Core.Interoperates;
global using System.Runtime.InteropServices;
global using WebKit;
global using GDisplay = Gdk.Display;
global using GSize = Gdk.Size;
global using GApplication = Gtk.Application;
global using GWidget = Gtk.Widget;
global using GWindow = Gtk.Window;
global using WebKitWebView = WebKit.WebView;
